version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:3000"
    restart: unless-stopped
    environment:
      - MONGODB_HOST=mongodb://mongo/${MONGODB_DATABASE}
      - TOKEN_STATIC=${TOKEN_STATIC}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: 'mongo:4.2.16-bionic'
    restart: always
    volumes:
      - ./db-data/mongo/:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge